import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginBottom: 16,
  },
  instructions: {
    color: '#666666',
    marginBottom: 8,
    fontSize: 14,
  },
  uploadContainer: {
    borderWidth: 1,
    borderRadius: 12,
    borderColor: '#e0e0e0',
    borderStyle: 'dashed',
    padding: 12,
    alignItems: 'center',
    backgroundColor: '#fafafa',
    marginVertical: 10,
  },
  uploadButton: {
    backgroundColor: '#6200ee',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    marginTop: 12,
    elevation: 2,
    shadowColor: '#6200ee',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  uploadButtonText: {
    color: 'white',
    fontWeight: '500',
    fontSize: 13,
  },
  fileInfoContainer: {
    marginTop: 8,
    padding: 8,
    backgroundColor: 'white',
    borderRadius: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  fileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  fileName: {
    flex: 1,
    marginLeft: 12,
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  iconContainer: {
    width: 25,
    height: 25,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  placeholderText: {
    color: '#757575',
    textAlign: 'center',
    marginTop: 8,
    fontSize: 14,
  },
  loadingContainer: {
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 8,
    color: '#6200ee',
    fontWeight: '500',
  },
  fileSize: {
    color: '#888',
    fontSize: 13,
    marginBottom: 12,
    fontWeight: '500',
  },
  fileActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 6,
    minWidth: 80,
    justifyContent: 'center',
  },
  downloadButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  deleteButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#f44336',
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '500',
  },
  downloadButtonText: {
    color: '#4CAF50',
  },
  deleteButtonText: {
    color: '#f44336',
  },
  formatsText: {
    color: '#9e9e9e',
    textAlign: 'center',
    marginTop: 4,
    fontSize: 11,
  },
}); 